#!/bin/bash +e
 
PROJECT="$(basename `pwd`)"
BUCKET="terraform.autojazari.mp.org"
 
init() {
  if [ -d .terraform ]; then
    if [ -e .terraform/terraform.tfstate ]; then
      echo "Remote state already exist!"
      if [ -z $IGNORE_INIT ]; then
        exit 1
      fi
    fi
  fi
 
 
  terraform remote config \
    -backend=s3 \
    -backend-config="bucket=${BUCKET}" \
    -backend-config="key=${PROJECT}/terraform.tfstate" \
    -backend-config="region=us-east-1"
 
}

remove_states() {
  if [ -a ".terraform/terraform.tfstate" ]
    then
      rm -rf .terraform/terraform.tfstate
  fi

  if [ -a "status" ]
    then
      rm -rf status
  fi

}

remove_states
init

for comp in "${Components[@]}"
do
  cd $PROJECT/$EnvStack/$comp
  terraform get
  terraform plan -out=plan.out -detailed-exitcode;
  if [ $? -eq 0 ]
    then
      terraform apply plan.out;
  else
    exit ;
  fi
done
